### PR TITLE
rebase against babel master

### PR DESCRIPTION
**Pull request by JuanCaicedo**
Hi @vincentdchan! 👋 I was having some trouble running `make bootstrap` on your branch with a cryptic error (which I included below).

I tried rebasing your branch against master. I'm not sure if I did it correctly, but that command succeeds now 😆

I thought to share it in case it can save you some time. But if this is not helpful, feel free to close this PR 😄
```
error Error parsing JSON at "https://raw.githubusercontent.com/kangax/compat-table/7c202e2da648fbd9d223d48d1680ec8f15147044/package.json", "Unexpected token : in JSON at position 3".
yarn install v1.6.0
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

    at Promise.all.then.arr (/Users/juan/code/speaking/babel/node_modules/execa/index.js:210:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:52731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:52731) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
make: *** [bootstrap] Error 1 
```

### CODE REVIEW

**Comment by JuanCaicedo** [comment]
I expect it might not be easy to merge this because of the conflicting changes 🙈 Glad to help if I can, but I will not be offended if you think it is easier to rebase your previous branch yourself 👍

**Comment by vincentdchan** [comment]
Great works! I know a lot of people are looking forward to the new pattern matching feature, but it's really a huge feature. The current proposal has a lot of differences from the old one when I implemented it. I am working on a new branch `feature/pattern-matching-statement` on my fork repo. The branch you try to rebase is abandoned, sorry I should have announced it.

**Comment by vincentdchan** [comment]
I abandoned the old version and I am re-implementing it, I have finished the parser, and I need to complete the **transforming** part, I am still planning how to implement it. If you have ideas, tell me and welcome to PR. 😄

**Comment by JuanCaicedo** [comment]
Awesome, I'll take a look at that branch!

**Pull request closed without merging**
